name: e-commerce_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pandas=2.2.1
  - numpy=1.26.4
  - scikit-learn=1.4.2
  - matplotlib=3.8.4
  - seaborn=0.12.2
  - jupyter=1.0.0
  - pip=24.0  
  - pip:
      - fastapi==0.111.0
      - xgboost==1.8.0
      - uvicorn==0.30.0
      - shap==0.42.1
      - joblib==1.4.2
      - kaggle==1.6.12
